export class EmailValidationUtils {
    private static validDomains = [
        'gmail.com',
        'outlook.com',
        'yahoo.com',
        'hotmail.com',
        'icloud.com',
        'protonmail.com',
        'aol.com',
        'live.com',
        'msn.com',
        'me.com',
        'mac.com',
        'googlemail.com',
        'ymail.com',
        'rocketmail.com',
        'fastmail.com',
        'zoho.com',
        'mail.com',
        'gmx.com',
        'web.de',
        't-online.de',
        'freenet.de',
        'arcor.de',
        'tiscali.it',
        'libero.it',
        'virgilio.it',
        'orange.fr',
        'laposte.net',
        'free.fr',
        'wanadoo.fr',
        'sfr.fr',
        'rediffmail.com',
        'indiatimes.com',
        'sify.com',
        'vsnl.net',
        'airtelmail.com',
        'bsnl.in',
        'mtnl.net.in'
    ];

    // Validate email domain - Case sensitive validation
    static validateEmailDomain(email: string): boolean {
        if (!email || !email.includes('@')) {
            return false;
        }
        
        // Get domain part exactly as entered (don't convert to lowercase)
        const domain = email.split('@')[1]?.trim();
        
        // Check if domain exists in valid domains (exact case match)
        return this.validDomains.includes(domain);
    }

    // Get list of valid domains (for reference)
    static getValidDomains(): string[] {
        return [...this.validDomains];
    }

    // Check if domain is temporary/disposable
    static isTemporaryDomain(email: string): boolean {
        const temporaryDomains = [
            'yopmail.com',
            'temp-mail.org',
            '10minutemail.com',
            'guerrillamail.com',
            'mailinator.com',
            'tempmail.com',
            'throwaway.email',
            'disposablemail.com',
            'temp-mail.ru',
            'sharklasers.com',
            'guerrillamailblock.com',
            'pokemail.net',
            'spam4.me',
            'bccto.me',
            'chacuo.net',
            'dispostable.com',
            'fakeinbox.com',
            'getairmail.com',
            'mailnesia.com',
            'maildrop.cc',
            'mailinator.net',
            'mintemail.com',
            'mytrashmail.com',
            'sharklasers.com',
            'spamspot.com',
            'tempr.email',
            'trashmail.com',
            'trashmail.net',
            'wegwerfemail.de',
            'wegwerfemail.net'
        ];

        const domain = email.split('@')[1]?.toLowerCase().trim();
        return temporaryDomains.includes(domain);
    }
}


export const validProviders = [
    // Popular UPI Apps
    'googlepay',
    'gpay',
    'phonepe',
    'paytm',
    'amazonpay',
    'bhim',
    'freecharge',
    'mobikwik',
    'airtelpay',
    'jio',
    'jiofin',
    'jiopay',
    
    // Major Banks
    'sbi',
    'oksbi',
    'hdfc',
    'okhdfc',
    'icici',
    'okicici',
    'axis',
    'okaxis',
    'pnb',
    'okpnb',
    'canara',
    'union',
    'okunion',
    'kotak',
    'okkotak',
    'yes',
    'okyes',
    'ybl',
    'okybl',
    'idfc',
    'okidfc',
    'rbl',
    'okrbl',
    'bob',
    'okbob',
    'iob',
    'okiob',
    'uco',
    'okuco',
    'psb',
    'okpsb',
    'centralbank',
    'okcentralbank',
    'indianbank',
    'okindianbank',
    
    // Finance Companies
    'bajaj',
    'bajajfinserv',
    'bajajpay',
    'okbajaj',
    'bajajfinance',
    'okbajajfinance',
    'bajajfin',
    'okbajajfin',
    
    // Other Popular Banks
    'fino',
    'okfino',
    'payzapp',
    'okpayzapp',
    'sbiunipay',
    'oksbiunipay',
    'hdfcpayzapp',
    'okhdfcpayzapp',
    'icicipay',
    'okicicipay',
    'axisbank',
    'okaxisbank',
    'pnbbank',
    'okpnbbank',
    'canarabank',
    'unionbank',
    'okunionbank',
    'kotakbank',
    'okkotakbank',
    'yesbank',
    'okyesbank',
    'idfcbank',
    'okidfcbank',
    'rblbank',
    'okrblbank',
    
    // More Banks
    'bankofbaroda',
    'okbankofbaroda',
    'bankofindia',
    'okbankofindia',
    'centralbankofindia',
    'okcentralbankofindia',
    'indianoverseasbank',
    'okindianoverseasbank',
    'punjabandsindbank',
    'okpunjabandsindbank',
    'uco',
    'okuco',
    'puduvai',
    'okpuduvai',
    'puduvaiurban',
    'okpuduvaiurban',
    'puduvaiurbancoop',
    'okpuduvaiurbancoop',
    'puduvaiurbancooperative',
    'okpuduvaiurbancooperative',
    'puduvaiurbancooperativebank',
    'okpuduvaiurbancooperativebank',
    
    // Regional Banks
    'karnataka',
    'okkarnataka',
    'andhra',
    'okandhra',
    'telangana',
    'oktelangana',
    'tamilnadu',
    'oktamilnadu',
    'kerala',
    'okkerala',
    'maharashtra',
    'okmaharashtra',
    'gujarat',
    'okgujarat',
    'rajasthan',
    'okrajasthan',
    'punjab',
    'okpunjab',
    'haryana',
    'okharyana',
    'delhi',
    'okdelhi',
    'up',
    'okup',
    'bihar',
    'okbihar',
    'jharkhand',
    'okjharkhand',
    'odisha',
    'okodisha',
    'westbengal',
    'okwestbengal',
    'assam',
    'okassam',
    'northeast',
    'oknortheast',
    
    // Generic UPI
    'upi',
    'okupi',
    'pay',
    'okpay',
    'money',
    'okmoney',
    'bank',
    'okbank',
    'transfer',
    'oktransfer',
    'send',
    'oksend',
    'receive',
    'okreceive',
    
    // Additional Popular
    'cred',
    'okcred',
    'groww',
    'okgroww',
    'zerodha',
    'okzerodha',
    'upstox',
    'okupstox',
    'angelone',
    'okangelone',
    'icicidirect',
    'okicicidirect',
    'hdfcsec',
    'okhdfcsec',
    'kotaksec',
    'okkotaksec',
    'axissec',
    'okaxissec',
    'sbinet',
    'oksbinet',
    'pnbnet',
    'okpnbnet',
    'unionnet',
    'okunionnet',
    'canaranet',
    'okcanaranet',
    'yesnet',
    'okyesnet',
    'idfcnet',
    'okidfcnet',
    'rblnet',
    'okrblnet',
    'bobnet',
    'okbobnet',
    'iobnet',
    'okiobnet',
    'uconet',
    'okuconet',
    'psbnet',
    'okpsbnet',
    'centralbanknet',
    'okcentralbanknet',
    'indianbanknet',
    'okindianbanknet'
];