export const summary =
    `
<ENVELOPE>
<HEADER>
<TALLYREQUEST>Export Data</TALLYREQUEST>
</HEADER>
<BODY>
<EXPORTDATA>
<REQUESTDESC>
<STATICVARIABLES>
<EXPLODEFLAG>YES</EXPLODEFLAG>
</STATICVARIABLES>
<REPORTNAME>Rpt_TNX_ExpClosing</REPORTNAME>
</REQUESTDESC>
</EXPORTDATA>
</BODY>
</ENVELOPE>
`